--[[
 .____                  ________ ___.    _____                           __                
 |    |    __ _______   \_____  \\_ |___/ ____\_ __  ______ ____ _____ _/  |_  ___________ 
 |    |   |  |  \__  \   /   |   \| __ \   __\  |  \/  ___// ___\\__  \\   __\/  _ \_  __ \
 |    |___|  |  // __ \_/    |    \ \_\ \  | |  |  /\___ \\  \___ / __ \|  | (  <_> )  | \/
 |_______ \____/(____  /\_______  /___  /__| |____//____  >\___  >____  /__|  \____/|__|   
         \/          \/         \/    \/                \/     \/     \/                   
          \_Welcome to LuaObfuscator.com   (Alpha 0.10.9) ~  Much Love, Ferib 

]]--

local v0=game:GetService("Players");local v1=game:GetService("UserInputService");local v2=setclipboard or toclipboard ;local v3=v0.LocalPlayer;local v4=v3:WaitForChild("PlayerGui");local v5=Instance.new("ScreenGui");v5.Name="LoadingAndKeyGui";v5.Parent=v4;v5.ResetOnSpawn=false;local v9=Instance.new("Frame");v9.Size=UDim2.new(1,0,1,0);v9.BackgroundColor3=Color3.new(0,0,0);v9.Parent=v5;local v13=Instance.new("TextLabel");v13.Size=UDim2.new(0.6,0,0.2,0);v13.Position=UDim2.new(0.2,0,0.3,0);v13.BackgroundTransparency=1;v13.TextColor3=Color3.new(1,1,1);v13.TextScaled=true;v13.Font=Enum.Font.GothamBold;v13.Text="Loading... 0%";v13.Parent=v9;local function v23() for v58=0,100 do v13.Text="Loading... "   .. tostring(v58)   .. "%" ;wait(0.03);end v13.Text="AntiCheat Bypass Wait";wait(2);end local function v24() for v60,v61 in pairs(v9:GetChildren()) do v61:Destroy();end local v26=Instance.new("TextLabel");v26.Size=UDim2.new(0.8,0,0.15,0);v26.Position=UDim2.new(0.1,0,0.25,0);v26.BackgroundTransparency=1;v26.TextColor3=Color3.new(1,1,1);v26.TextScaled=true;v26.Font=Enum.Font.GothamBold;v26.Text="Key System";v26.Parent=v9;local v36=Instance.new("TextBox");v36.Size=UDim2.new(0.5,0,0.1,0);v36.Position=UDim2.new(0.25,0,0.45,0);v36.BackgroundColor3=Color3.fromRGB(30,30,30);v36.TextColor3=Color3.new(1,1,1);v36.Font=Enum.Font.Gotham;v36.PlaceholderText="Enter key here";v36.TextScaled=true;v36.ClearTextOnFocus=false;v36.TextEditable=false;v36.Active=false;v36.Parent=v9;local v49=Instance.new("TextButton");v49.Size=UDim2.new(0.3,0,0.1,0);v49.Position=UDim2.new(0.35,0,0.6,0);v49.BackgroundColor3=Color3.fromRGB(80,80,80);v49.TextColor3=Color3.new(1,1,1);v49.Font=Enum.Font.GothamBold;v49.TextScaled=true;v49.Text="Discord";v49.Parent=v9;v49.MouseButton1Click:Connect(function() if v2 then v2("https://discord.gg/ZtAhGYCsXS");v49.Text="Copied!";wait(2);v49.Text="Discord";else v49.Text="No clipboard";wait(2);v49.Text="Discord";end end);end spawn(function() v23();v24();end);